# sample config defaults file
model:
  epochs: 20
  batch_size: 32
  lr: 0.00001
  channels: 3
  weight_decay: 0
  no_of_workers: 2
  pin_memory: True
  load_model: False
  save_model: True
  model_save_path: ../../data/trained_models/play_noplay/best-model-parameters-eff-b0.pt
  model_load_path: ../../data/trained_models/play_noplay/best-model-parameters-eff-b0.pt
  input_width: 224
  input_height: 224
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]

data:
  image_dir: ../../data/dataset_pnp/
  image_train_dir: train
  image_test_dir: test
  image_val_dir: val
  class_names:
    - play
    - noplay
  no_of_classes: 2